#!/usr/bin/env python3
"""Regenerate ``server/app/tool_flags.py`` from the engine's own argparse parsers.

The engine is the source of truth for which flags each tool accepts. Run this from the repo root whenever a
tool's ``add_arguments`` changes, then commit the updated module:

    python scripts/gen_tool_flags.py
"""
from __future__ import annotations

import argparse
import importlib
import pkgutil
from pathlib import Path

import boxcutter.tools as T


def collect() -> dict[str, list[str]]:
    tools: dict[str, list[str]] = {}
    for m in pkgutil.iter_modules(T.__path__):
        if m.name.startswith("_"):
            continue
        try:
            mod = importlib.import_module(f"boxcutter.tools.{m.name}")
        except Exception:  # noqa: BLE001 - skip a tool that can't import in this env
            continue
        name, add = getattr(mod, "NAME", None), getattr(mod, "add_arguments", None)
        if not name or not add:
            continue
        p = argparse.ArgumentParser(prog=name, add_help=False)
        try:
            add(p)
        except Exception:  # noqa: BLE001
            continue
        tools[name] = sorted({s for a in p._actions for s in a.option_strings if s.startswith("-")})
    return tools


def render(tools: dict[str, list[str]]) -> str:
    lines = ["    \"%s\": %s," % (name, flags) for name, flags in sorted(tools.items())]
    body = "\n".join(lines)
    return (
        '"""Accepted CLI flags per boxcutter tool — the source of truth for argument validation in the UI.\n\n'
        "Generated by scripts/gen_tool_flags.py from the engine's argparse parsers. Do not edit by hand.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "TOOL_FLAGS: dict[str, list[str]] = {\n" + body + "\n}\n"
    )


if __name__ == "__main__":
    tools = collect()
    print(f"collected {len(tools)} tools")
    # Only prints the data block — the hand-maintained module also carries the validator (unknown_flags). Paste
    # the TOOL_FLAGS block below into server/app/tool_flags.py, keeping the helper functions.
    print(render(tools))
